const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART"
const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART"
const DECREASE_ITEM_QUANTITY_FROM_CART = "DECREASE_ITEM_QUANTITY_FROM_CART"
const TOGGLE_CART_OPEN = "TOGGLE_CART_OPEN"
const GET_CART_ITEMS_COUNT = "GET_CART_ITEMS_COUNT"
const GET_CART_ITEMS_TOTAL_PRICE = "GET_CART_ITEMS_TOTAL_PRICE"
const SET_CART_STAGE = "SET_CART_STAGE"
const CLEAR_CART = "CLEAR_CART"

export {
  ADD_ITEM_TO_CART,
  REMOVE_ITEM_FROM_CART,
  DECREASE_ITEM_QUANTITY_FROM_CART,
  TOGGLE_CART_OPEN,
  GET_CART_ITEMS_COUNT,
  GET_CART_ITEMS_TOTAL_PRICE,
  SET_CART_STAGE,
  CLEAR_CART,
}
